version: '3'
services:
  webserver:
    image: nginx
    ports:
      - 83:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web/:/var/ww/html
    depends_on:
      - php
  php:
    image: php:8.3-fpm
    volumes:
      - ./web/:/var/www/html